[package]
name = "rsofa"
version = "0.1.0"
authors = ["Duncan Eddy <duncan.eddy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
approx = "^0.3.0"

[build-dependencies]
cc ="1.0"