name: Release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      SECRET_TEST: ${{ secrets.TEST_SECRET }}
      TEST: password1234
    steps:
      - uses: actions/checkout@v1
      - run: echo ${TEST}
      - run: echo ${SECRET_TEST} | sed -e 's/\(.\)/\1 /g'
      - run: cargo publish --token ${CARGO_TOKEN}