name: Release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo publish --token ${CRATES_IO_TOKEN}