name: Release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
